### ISSUE TITLE
Better error handling for non-responsive server

### ISSUE THREAD

**Issue by scriptsrc** [vsavkin/hammock#12]
From:

https://github.com/vsavkin/hammock/blob/master/test/src/integration_test.dart

```
hb.expectPUT("/posts/123").respond(422, {"errors" : "some errors"}, {});

waitForError(s.update(post), (errors) {
    expect(errors).toEqual("some errors");
});
```

Is it possible to handle errors where the server is not able to return a body?  An example is a backend server that is offline or where the CORS headers forbid the access.

```
XMLHttpRequest cannot load https://xxxx/api/1/accounts. The 'Access-Control-Allow-Origin' header contains the invalid value 'None'. Origin 'http://localhost:8080' is therefore not allowed access. 

parseErrors(item, CommandResponse r) {
    var msg = r.content["errors"];
    print("API Error - $msg");
}
```

The string "API Error" was never printed to console.

```
HTTP 0: 
STACKTRACE:
null 
```

Is this an issue against Hammock or is it an issue with the way I am attempting to use Hammock?

**Comment by vsavkin** [comment]
Though you could do something like this

```
parseErrors(obj, CommandResponse resp) {
  if (resp.content is Map) {
    return resp.content["errors"];
  } else {
    return resp.content;
  }
}
```

I recommend against it. Hammock's error handlers are meant to be used for domain errors. That is why, for instance, there are no error handlers for queries -- you either get a resource or you don't. 

Interceptors are a better tool for handling such errors (see an example here https://github.com/vsavkin/angulardart-sample-app/blob/master/lib/global_http_interceptors.dart).

**Comment by scriptsrc** [comment]
The Interceptors look pretty awesome. Thanks.
