### ISSUE TITLE
Incompatible DI package version constraints with Angular 0.14.0

### ISSUE THREAD

**Issue by kemallette** [vsavkin/hammock#13]
Output from pub get is:

```
Incompatible version constraints on di:
- angular 0.14.0 depends on version >=2.0.1 <3.0.0
- hammock 0.2.4 depends on version >=0.0.40 <0.1.0
```

I figured I'd try overriding the di dependency just to see if it would work and I got: 

```
Resolving dependencies...
> hammock 0.2.4 (was 0.2.2)
Warning: You are using these overridden dependencies:
! di 2.0.2
Downloading hammock 0.2.4...
// This below repeats several more times
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
Changed 1 dependency!
```

This is unfortunate, since I was looking forward to refactoring to use the new request defaults feature. 

Thanks for all your hard work on this package and let me know if you need any more info. :)

**Comment by vsavkin** [comment]
I've updated pubspec.yaml. You should be able to use hammock with angular 0.14.0.

**Comment by kemallette** [comment]
Excellent! Thanks for such a quick resolution. I know you're busy on Angular.dart.
