### ISSUE TITLE
List with pagination metadata

### ISSUE THREAD

**Issue by scriptsrc** [vsavkin/hammock#14]
I'm working with an API endpoint that returns pagination data along with the returned objects:

```
GET /api/1/widgets?count=5&page=5
{
    "count": 3, 
    "widgets": [
        {
            ...
        }, 
        {
            ...
        }, 
        {
            ...
        }
    ], 
    "page": 5, 
    "total": 23
}
```

I'd like to have the list method return this pagination data (count,page,total).  Currently the list method only returns the list of deserialized widgets:

```
store.list(Widget,
    params: {
        "count": _items_per_page,
        "page": currentPage
    }).then((List<Widget> widgets) {
        this.widgets = widgets;
        _is_loaded = true;
});
```

Is there a way to also get the pagination metadata?

```
store.list(Widget,
    params: {
        "count": _items_per_page,
        "page": currentPage
    }).then((List<Widget> widgets, int count, int page, int total) {
        this.widgets = widgets;
        _is_loaded = true;
        this.count = count;
        this.page = page;
        this.total = total;
});
```

A global http interceptor would not work well here because multiple list queries are being fired off in parallel against different resources.  I guess the interceptor could look at the request to determine which scope to message these values to, but that seems a little messy.

Is there an easy way to modify `List<Resource> jsonToManyResources(type, json)` to also return this metadata?

**Comment by vsavkin** [comment]
I think this is a pretty common use case, and Hammock should support it.

The options I like the most are

``` dart
class ResultSet implements List {
    Map get  pagination;
}
```

And

```
class ResultSet {
    List get list;
    Map get pagination;
}
```

```
ResultSet list(...)
```

I'll try to do it this week.
