### ISSUE TITLE
jsonToManyResources return type

### ISSUE THREAD

**Issue by scriptsrc** [vsavkin/hammock#15]
```
List<Resource> jsonToManyResources(type, json) =>
      json[type].map((r) => resource(type, r["id"], r));
```

This code works when running as javascript in Chrome.

When running in Dartium, I get the following error:

```
type 'MappedListIterable' is not a subtype of type 'List<Resource>' of 'function result'.
```

**Comment by vsavkin** [comment]
You probably run Dartium in the checked mode, and that is why the issue manifests only in Dartium. This is a bug.
