### ISSUE TITLE
Update angular.dart dependency to v1.0.0?

### ISSUE THREAD

**Issue by adarshaj** [vsavkin/hammock#17]
current [pubspec.yaml](https://github.com/vsavkin/hammock/blob/8e698e50379714613af2042f90cf159c03feea9f/pubspec.yaml) prevents it from being used with angular v1.0.0, is it planned to be upgraded soon?

**Comment by scriptsrc** [comment]
+1

**Comment by scriptsrc** [comment]
Dart Editor does not flag any issues when upgrading the pubspec.yaml:

```
angular: '1.0.0'
di: '>=3.3.1 <4.0.0'
```

I need to figure out how to use angular_guinness and run the tests to see if anything really breaks.  Guess I'll see if I can learn how to do that now.

**Comment by scriptsrc** [comment]
I got the tests passing with one minor change.  Hopefully Victor can chime in if this is not the correct fix.

test/src/integration_test.dart line 31 needs a whenPUT:

```
hb.whenPUT("/posts/123").respond({"posts" : [{"id" : 123, "title" : "new"}]});
```

---

```
  describe("Custom Document Formats", () {
    it("can support jsonapi.org format", (HammockConfig config, MockHttpBackend hb, ResourceStore s){
      config.documentFormat = new JsonApiOrgFormat();

      hb.whenGET("/posts/123").respond({"posts" : [{"id" : 123, "title" : "title"}]});
      wait(s.one("posts", 123), (post) {
        expect(post.content["title"]).toEqual("title");
      });

      hb.whenPUT("/posts/123").respond({"posts" : [{"id" : 123, "title" : "new"}]});
      hb.expectPUT("/posts/123", '{"posts":[{"id":123,"title":"new"}]}');
      wait(s.update(resource("posts", 123, {"id" : 123, "title" : "new"})));
    });
  });
```

After that, all tests are passing:

```
(hammock)➜  hammock git:(master) ✗ karma start
INFO [karma]: Karma v0.12.24 server started at http://localhost:9876/
INFO [launcher]: Starting browser Dartium
INFO [Chrome 37.0.2062 (Mac OS X 10.10.0)]: Connected on socket s2fAztMgE575qf0u7yUu with id 35687617
Chrome 37.0.2062 (Mac OS X 10.10.0) DUMP: unittest-suite-wait-for-done

Chrome 37.0.2062 (Mac OS X 10.10.0): Executed 47 of 47 SUCCESS (0.624 secs / 0.585 secs)
```

Without the whenPUT, we get this error:

```
Chrome 37.0.2062 (Mac OS X 10.10.0) Custom Document Formats can support jsonapi.org format FAILED
Test failed: Caught [No response defined !]
```

**Comment by adarshaj** [comment]
@vsavkin bump! any updates on this? I've been using with dependency override and it just seems to work, any plans to upgrade?

thanks,

**Comment by vsavkin** [comment]
Sorry it took so long. Just pushed the updated version https://pub.dartlang.org/packages/hammock.

**Comment by adarshaj** [comment]
:+1:

**Comment by scriptsrc** [comment]
The demo pubspec is still limited to <1.0.0:
https://github.com/vsavkin/hammock/blob/master/demo/pubspec.yaml#L5

Also, the mirror_based_serializer.dart imports dart:mirrors without a @MirrorsUsed() attribute.
import 'dart:mirrors';
https://github.com/vsavkin/hammock/blob/master/demo/web/util/mirror_based_serializers.dart#L3

May be better to change the models to actual objects so you can enumerate them in @MirrorsUsed()

**Comment by vsavkin** [comment]
@monkeysecurity could you submit a PR?

**Comment by scriptsrc** [comment]
@vsavkin Will do. Give me a day or two.
