### ISSUE TITLE
pubspec.yaml is missing http_server dependency

### ISSUE THREAD

**Issue by scriptsrc** [vsavkin/hammock#18]
demo/server.dart line 5 references http_server:

```
import 'package:http_server/http_server.dart' show VirtualDirectory;
```

pubspec.yaml does not currently contain a dependency on http_server.

```
  http_server: '0.9.3'
```

That seems to do it.

Because the dependency is in the demo code, and not in the library itself, it feels a little weird to add the dependency to pubspec.yaml.

**Comment by vsavkin** [comment]
I'm probably missing something, but I believe pubspec.ymal in the demo directory has the dependency: https://github.com/vsavkin/hammock/blob/master/demo/pubspec.yaml.
